project_id = "pulse-platform-local"

[auth]
site_url = "http://127.0.0.1:8082"
additional_redirect_urls = ["http://localhost:8082"]

[analytics]
enabled = false

[functions.payments-webhook]
verify_jwt = false

[functions.criar-checkout-stripe]
verify_jwt = false

[functions.criar-checkout-plano]
verify_jwt = false

[functions.criar-checkout-premium]
verify_jwt = false
