// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

import { LOCAL_PREVIEW, previewFetch } from '@/lib/local-preview';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(LOCAL_PREVIEW ? 'http://127.0.0.1:54321' : SUPABASE_URL, LOCAL_PREVIEW ? 'local-preview-public-key' : SUPABASE_PUBLISHABLE_KEY, {
  ...(LOCAL_PREVIEW ? { global: { fetch: previewFetch } } : {}),
  auth: {
    storage: localStorage,
    persistSession: !LOCAL_PREVIEW,
    autoRefreshToken: !LOCAL_PREVIEW,
    detectSessionInUrl: !LOCAL_PREVIEW,
    ...(LOCAL_PREVIEW ? { storageKey: "pulse-preview-auth" } : {}),
  }
});